apiVersion: v1
kind: Namespace
metadata:
  name: leocinema
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: leocinema-configmap
  namespace: leocinema
data:
  FRONTEND_URL: "http://172.171.58.32"
  BACKEND_URL: "172.171.58.32/api/comprar-ingresso"
---
apiVersion: v1
kind: Secret
metadata:
  name: leocinema-secrets
  namespace: leocinema
type: Opaque
data:
  DB_HOST: bWFyaWFkYi1sZW9jaW5lbWEtc3Zj
  MARIADB_ROOT_PASSWORD: bGVvYm9yZ2VzMzAwNQ==
  MARIADB_DATABASE: bGVvY2luZW1hZGI=
  MARIADB_USER: bGVvY2luZW1hdXNlcg==
  MARIADB_PASSWORD: bGVvY2luZW1hcGFzcw==