apiVersion: v1
kind: Service
metadata:
  name: {{ include "leocinema.name" . }}-backend-svc
  labels:
    app: {{ include "leocinema.name" . }}-backend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: 3333
  selector:
    app: {{ include "leocinema.name" . }}-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leocinema.name" . }}-backend-dep
  labels:
    app: {{ include "leocinema.name" . }}-backend
spec:
  replicas: {{ .Values.backend.minReplicas }}
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
  selector:
    matchLabels:
      app: {{ include "leocinema.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "leocinema.name" . }}-backend
    spec:
      {{- if .Values.nodeSelectorEnabled }}
      nodeSelector:
        tier: "app"
      {{- end }}
      containers:
        - name: leocinema
          image: "{{ .Values.backend.image }}"
          livenessProbe:
            httpGet:
              path: /health
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: http
              containerPort: 3333
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "leocinema.name" . }}-secrets
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "leocinema.name" . }}-secrets
                  key: DB_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "leocinema.name" . }}-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "leocinema.name" . }}-secrets
                  key: DB_PASSWORD
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "leocinema.name" . }}-configmap
                  key: FRONTEND_URL
          resources:
            requests:
              cpu: {{ .Values.backend.cpu }}
              memory: {{ .Values.backend.memory }}
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
      restartPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "leocinema.name" . }}-backend-hpa
spec:
  maxReplicas: {{ .Values.backend.maxReplicas }}
  minReplicas: {{ .Values.backend.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "leocinema.name" . }}-backend-dep
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.averageUtilization }}
{{- if .Values.ingressEnabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "leocinema.name" . }}-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host:
      http:
        paths:
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "leocinema.name" . }}-backend-svc
                port:
                  number: {{ .Values.backend.servicePort }}
{{- end }}